/** Common ElevenLabs shared-voice language codes (sorted A–Z, "All" first). */
export const VOICE_LIBRARY_LANGUAGES = [
  { value: "all", label: "All languages" },
  { value: "zh", label: "Chinese" },
  { value: "en", label: "English" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "hi", label: "Hindi" },
  { value: "it", label: "Italian" },
  { value: "ja", label: "Japanese" },
  { value: "ko", label: "Korean" },
  { value: "pl", label: "Polish" },
  { value: "pt", label: "Portuguese" },
  { value: "es", label: "Spanish" },
] as const;

/** Accent / region filters from ElevenLabs voice library (151 values). */
export const VOICE_LIBRARY_ACCENTS = [
  { value: "all", label: "All accents" },
  { value: "acadian", label: "Acadian" },
  { value: "aegean", label: "Aegean" },
  { value: "african", label: "African" },
  { value: "african american", label: "African American" },
  { value: "american", label: "American" },
  { value: "anatolian", label: "Anatolian" },
  { value: "andalusian", label: "Andalusian" },
  { value: "arabic", label: "Arabic" },
  { value: "argentine", label: "Argentine" },
  { value: "athenian", label: "Athenian" },
  { value: "australian", label: "Australian" },
  { value: "awadhi", label: "Awadhi" },
  { value: "bavarian", label: "Bavarian" },
  { value: "beijing mandarin", label: "Beijing Mandarin" },
  { value: "belgian", label: "Belgian" },
  { value: "bengali", label: "Bengali" },
  { value: "berlinerisch", label: "Berlinerisch" },
  { value: "bhojpuri", label: "Bhojpuri" },
  { value: "bihari", label: "Bihari" },
  { value: "boston", label: "Boston" },
  { value: "brabantian", label: "Brabantian" },
  { value: "brazilian", label: "Brazilian" },
  { value: "british", label: "British" },
  { value: "bucovina", label: "Bucovina" },
  { value: "budapest", label: "Budapest" },
  { value: "calabrese", label: "Calabrese" },
  { value: "canadian", label: "Canadian" },
  { value: "canary islands", label: "Canary Islands" },
  { value: "caribbean", label: "Caribbean" },
  { value: "cebuano", label: "Cebuano" },
  { value: "central", label: "Central" },
  { value: "chennai", label: "Chennai" },
  { value: "chicago", label: "Chicago" },
  { value: "chilean", label: "Chilean" },
  { value: "chinese", label: "Chinese" },
  { value: "chungcheong", label: "Chungcheong" },
  { value: "colombian", label: "Colombian" },
  { value: "copenhagen", label: "Copenhagen" },
  { value: "creole", label: "Creole" },
  { value: "croatian", label: "Croatian" },
  { value: "cuban", label: "Cuban" },
  { value: "cypriot", label: "Cypriot" },
  { value: "czech", label: "Czech" },
  { value: "danish", label: "Danish" },
  { value: "dominican", label: "Dominican" },
  { value: "dutch", label: "Dutch" },
  { value: "ecuadorian", label: "Ecuadorian" },
  { value: "egyptian", label: "Egyptian" },
  { value: "european", label: "European" },
  { value: "filipino", label: "Filipino" },
  { value: "finnish", label: "Finnish" },
  { value: "flemish", label: "Flemish" },
  { value: "florentine", label: "Florentine" },
  { value: "french", label: "French" },
  { value: "galician", label: "Galician" },
  { value: "german", label: "German" },
  { value: "gothenburg", label: "Gothenburg" },
  { value: "greek", label: "Greek" },
  { value: "gujarati", label: "Gujarati" },
  { value: "gulf", label: "Gulf" },
  { value: "gyeongsang", label: "Gyeongsang" },
  { value: "haryanvi", label: "Haryanvi" },
  { value: "helsinki", label: "Helsinki" },
  { value: "hindi", label: "Hindi" },
  { value: "hong kong cantonese", label: "Hong Kong Cantonese" },
  { value: "indian", label: "Indian" },
  { value: "indonesian", label: "Indonesian" },
  { value: "iraqi", label: "Iraqi" },
  { value: "irish", label: "Irish" },
  { value: "istanbul", label: "Istanbul" },
  { value: "italian", label: "Italian" },
  { value: "jamaican", label: "Jamaican" },
  { value: "japanese", label: "Japanese" },
  { value: "javanese", label: "Javanese" },
  { value: "jeolla", label: "Jeolla" },
  { value: "jordanian", label: "Jordanian" },
  { value: "kansai", label: "Kansai" },
  { value: "kanto", label: "Kanto" },
  { value: "kashubian", label: "Kashubian" },
  { value: "khariboli", label: "Khariboli" },
  { value: "kiev", label: "Kiev" },
  { value: "korean", label: "Korean" },
  { value: "kuwaiti", label: "Kuwaiti" },
  { value: "kyushu", label: "Kyushu" },
  { value: "latin american", label: "Latin American" },
  { value: "levantine", label: "Levantine" },
  { value: "madeiran", label: "Madeiran" },
  { value: "malay", label: "Malay" },
  { value: "malaysian", label: "Malaysian" },
  { value: "marathi", label: "Marathi" },
  { value: "mazovian", label: "Mazovian" },
  { value: "meridional", label: "Meridional" },
  { value: "mexican", label: "Mexican" },
  { value: "milanese", label: "Milanese" },
  { value: "modern standard", label: "Modern Standard" },
  { value: "moravian", label: "Moravian" },
  { value: "moroccan", label: "Moroccan" },
  { value: "moscow", label: "Moscow" },
  { value: "new york", label: "New York" },
  { value: "new zealand", label: "New Zealand" },
  { value: "nigerian", label: "Nigerian" },
  { value: "northern", label: "Northern" },
  { value: "oslo", label: "Oslo" },
  { value: "parisian", label: "Parisian" },
  { value: "peninsular", label: "Peninsular" },
  { value: "peruvian", label: "Peruvian" },
  { value: "polish", label: "Polish" },
  { value: "portuguese", label: "Portuguese" },
  { value: "prague", label: "Prague" },
  { value: "puerto rican", label: "Puerto Rican" },
  { value: "punjabi", label: "Punjabi" },
  { value: "quebec", label: "Quebec" },
  { value: "rajasthani", label: "Rajasthani" },
  { value: "received pronunciation", label: "Received Pronunciation" },
  { value: "rhine franconian", label: "Rhine Franconian" },
  { value: "romanesco", label: "Romanesco" },
  { value: "romanian", label: "Romanian" },
  { value: "russian", label: "Russian" },
  { value: "saint petersburg", label: "Saint Petersburg" },
  { value: "saudi", label: "Saudi" },
  { value: "saxon", label: "Saxon" },
  { value: "scanian", label: "Scanian" },
  { value: "scottish", label: "Scottish" },
  { value: "scouse", label: "Scouse" },
  { value: "seoul", label: "Seoul" },
  { value: "sicilian", label: "Sicilian" },
  { value: "singaporean", label: "Singaporean" },
  { value: "slovak", label: "Slovak" },
  { value: "sofia", label: "Sofia" },
  { value: "south african", label: "South African" },
  { value: "southern", label: "Southern" },
  { value: "spanish", label: "Spanish" },
  { value: "standard", label: "Standard" },
  { value: "stockholm", label: "Stockholm" },
  { value: "swabian", label: "Swabian" },
  { value: "swedish", label: "Swedish" },
  { value: "syrian", label: "Syrian" },
  { value: "taiwan mandarin", label: "Taiwan Mandarin" },
  { value: "tamil", label: "Tamil" },
  { value: "tunisian", label: "Tunisian" },
  { value: "turkish", label: "Turkish" },
  { value: "tuscan", label: "Tuscan" },
  { value: "ukrainian", label: "Ukrainian" },
  { value: "us midwest", label: "Us Midwest" },
  { value: "us northeast", label: "Us Northeast" },
  { value: "us southern", label: "Us Southern" },
  { value: "venezuelan", label: "Venezuelan" },
  { value: "welsh", label: "Welsh" },
  { value: "western", label: "Western" },
  { value: "yorkshire", label: "Yorkshire" },
  { value: "zagreb", label: "Zagreb" },
] as const;
